# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno"
version = "1.5.2"
license = "MIT"
authors = ["the Deno authors"]
edition = "2018"
description = "Provides the deno executable"
repository = "https://github.com/denoland/deno"
default-run = "deno"

[[bin]]
name = "deno"
path = "main.rs"

[[bench]]
name = "deno_bench"
harness = false
path = "./bench/main.rs"

[build-dependencies]
deno_crypto = { path = "../op_crates/crypto", version = "0.1.1" }
deno_core = { path = "../core", version = "0.67.0" }
deno_web = { path = "../op_crates/web", version = "0.18.0" }
deno_fetch = { path = "../op_crates/fetch", version = "0.10.0" }
regex = "1.3.9"
serde = { version = "1.0.116", features = ["derive"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = "0.3.9"

[dependencies]
deno_crypto = { path = "../op_crates/crypto", version = "0.1.1" }
deno_core = { path = "../core", version = "0.67.0" }
deno_doc = "0.1.15"
deno_lint = "0.2.9"
deno_web = { path = "../op_crates/web", version = "0.18.0" }
deno_fetch = { path = "../op_crates/fetch", version = "0.10.0" }

atty = "0.2.14"
base64 = "0.12.3"
bytes = "0.5.6"
byteorder = "1.3.4"
clap = "2.33.3"
dissimilar = "1.0.2"
dlopen = "0.1.8"
encoding_rs = "0.8.24"
dprint-plugin-typescript = "0.32.8"
filetime = "0.2.12"
http = "0.2.1"
indexmap = "1.6.0"
jsonc-parser = "0.14.0"
lazy_static = "1.4.0"
libc = "0.2.77"
log = "0.4.11"
env_logger = "0.7.1"
notify = "5.0.0-pre.3"
regex = "1.3.9"
ring = "0.16.15"
rustyline = { version = "6.3.0", default-features = false }
rustyline-derive = "0.3.1"
serde = { version = "1.0.116", features = ["derive"] }
shell-escape = "0.1.5"
sys-info = "0.7.0"
sourcemap = "6.0.1"
swc_bundler = "=0.16.1"
swc_common = { version = "=0.10.5", features = ["sourcemap"] }
swc_ecmascript = { version = "=0.13.3", features = ["codegen", "dep_graph", "parser", "react", "transforms", "visit"] }
tempfile = "3.1.0"
termcolor = "1.1.0"
tokio = { version = "0.2.22", features = ["full"] }
tokio-rustls = "0.14.1"
# Keep in-sync with warp.
tokio-tungstenite = "0.11.0"
webpki = "0.21.3"
webpki-roots = "=0.19.0" # Pinned to v0.19.0 to match 'reqwest'.
walkdir = "2.3.1"
warp = { version = "0.2.5", features = ["tls"] }
semver-parser = "0.9.0"
uuid = { version = "0.8.1", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }
fwdansi = "1.1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.20.2"

[dev-dependencies]
# Used in benchmark
chrono = "0.4.15"
os_pipe = "0.9.2"
test_util = { path = "../test_util" }

[package.metadata.winres]
# This section defines the metadata that appears in the deno.exe PE header.
OriginalFilename = "deno.exe"
LegalCopyright = "© Deno contributors & Deno Land Inc. MIT licensed."
ProductName = "Deno"
FileDescription = "A secure runtime for JavaScript and TypeScript."
