# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
[package]
name = "deno_core"
version = "0.67.0"
edition = "2018"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0.32"
futures = "0.3.5"
indexmap = "1.6.0"
lazy_static = "1.4.0"
libc = "0.2.77"
log = "0.4.11"
rusty_v8 = "0.12.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.6.1"
url = { version = "2.1.1", features = ["serde"] }

[[example]]
name = "http_bench_bin_ops"
path = "examples/http_bench_bin_ops.rs"

[[example]]
name = "http_bench_json_ops"
path = "examples/http_bench_json_ops.rs"

# These dependendencies are only used for the 'http_bench_*_ops' examples.
[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
